name: Docs
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nocturlab/setup-vlang-action@master
        with:
          v-version: master
      - name: Generate documentation
        uses: test-room-7/action-create-v-docs@v0
        with:
          docs-dir: docs
      - name: Update documentation
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/*
          commit-msg: Update documentation
          github-token: ${{ secrets.GITHUB_TOKEN }}
